### ISSUE TITLE
Minyeong Kang

### ISSUE THREAD

**Issue by jinjukang67** [koco-tunlp/math-challenge#1]
![toonmecom_c1731b](https://user-images.githubusercontent.com/75985245/172203397-cda63654-3c58-4d82-a60c-1a547d7d4e2b.jpg)

**Comment by dlfrnaos19** [comment]
이미지 업로드를 위한 이슈였네요
이슈에 이미지 저장까지는 안하셔도 됩니다 ㅎㅎ
